# ace_trading/config_graph_vector.py
"""
Configuration for Graph Database (Neo4j) and Vector Database (LSTM) integration.
Defines base states, dynamic state naming conventions, and database connection parameters.
"""

import os

# ============================================================================
# NEO4J GRAPH DATABASE CONFIGURATION
# ============================================================================

NEO4J_URI = os.getenv("NEO4J_URI", "bolt://localhost:7687")
NEO4J_USER = os.getenv("NEO4J_USER", "neo4j")
NEO4J_PASSWORD = os.environ["NEO4J_PASSWORD"]  # 强制要求设置环境变量

# Whether to enable graph DB features (insert reflections, query insights)
GRAPH_DB_ENABLED = True

# ============================================================================
# VECTOR DATABASE CONFIGURATION
# ============================================================================

VECTOR_DB_MODEL_PATH = r"D:\BTC_ACE\ace_trading\LSTM\models\btc_lstm_attn_model_2024-06-01.pth"
VECTOR_DB_TOP_K = 5  # Number of similar patterns to retrieve per query
VECTOR_DB_DEVICE = 'cuda'  # or 'cpu' if CUDA not available

# Whether to enable vector DB features (similarity search)
VECTOR_DB_ENABLED = True

# ============================================================================
# BASE STATES - Predefined for Agent S Initial Analysis
# ============================================================================

BASE_STATES = {
    'rsi': [
        'RSI_Oversold',      # RSI < 30
        'RSI_Overbought',    # RSI > 70
        'RSI_Neutral',       # 30 <= RSI <= 70
    ],
    'volume': [
        'Vol_Spike',         # Volume > 1.5x MA
        'Vol_Dry',           # Volume < 0.7x MA
    ],
    'sentiment': [
        'Bull_Sentiment',    # MACD > 0 and price > 20-MA
        'Bear_Sentiment',    # MACD < 0 and price < 20-MA
    ],
    'funding': [
        'Funding_Rate_High',  # Funding rate > 0.05% per 8h
        'Funding_Rate_Low',   # Funding rate < 0%
    ],
    'openinterest': [
        'OI_Rising',         # Open interest increasing > 5% in window
        'OI_Falling',        # Open interest decreasing > 5% in window
    ],
    'time': [
        'Friday_Afternoon',  # Day == Friday (4) AND hour >= 14
        'London_Open',       # Hour == 8 (London market open)
        'US_MarketHours',    # 13 <= hour < 21 (US market)
    ],
    'price': [
        'Price_AtSupport',      # Price within 1% of support level
        'Price_AtResistance',   # Price within 1% of resistance level
    ],
}

# Flatten all base states into a single list for Agent S
ALL_BASE_STATES = []
for category, states in BASE_STATES.items():
    ALL_BASE_STATES.extend(states)

# ============================================================================
# DYNAMIC STATE GENERATION - For Agent C During Reflection
# ============================================================================

# Pattern for dynamic state names generated by Agent C
DYNAMIC_STATE_NAMING_RULE = "[Category]_[Condition]_[Threshold/Timeframe]"

# Examples of valid dynamic state names:
DYNAMIC_STATE_EXAMPLES = [
    'MACD_GoldenCross_1h',              # MACD fast line crosses above slow line on 1h
    'Price_BreakoutAbove_Resistance_4H', # Price breaks above 4h resistance level
    'RSI_DivergenceNegative_15m',        # Bearish divergence on 15m
    'Volume_ClimbingWedge_30min',        # Volume climbing wedge pattern over 30 min
    'Funding_SpikePositive_1h',          # Funding rate jumps 50%+ in 1 hour
    'Sentiment_FlipBullish',             # Market sentiment changed from bear to bull
]

# Only Agent C can generate new states (not Agent S or A)
DYNAMIC_STATE_CREATION_AGENT = "Agent_C"

# ============================================================================
# EVENT ID FORMAT
# ============================================================================

# Format: YYYYMMDD_HHMMSS_[P|R]
# P = Planned trade (Agent B approved)
# R = Reflection only (Agent B rejected)
EVENT_ID_FORMAT = "YYYYMMDD_HHMMSS_[P|R]"

# ============================================================================
# STATE THRESHOLDS FOR DETECTION
# ============================================================================

# RSI thresholds
RSI_OVERSOLD_THRESHOLD = 30
RSI_OVERBOUGHT_THRESHOLD = 70

# Volume thresholds (ratio to moving average)
VOL_SPIKE_RATIO = 1.5      # Volume > 1.5x MA = Vol_Spike
VOL_DRY_RATIO = 0.7        # Volume < 0.7x MA = Vol_Dry

# Funding rate thresholds (per 8 hours)
FUNDING_RATE_HIGH_THRESHOLD = 0.0005   # 0.05%
FUNDING_RATE_LOW_THRESHOLD = 0.0        # Negative funding

# Open interest thresholds
OI_CHANGE_THRESHOLD = 0.05  # 5% change = OI_Rising/OI_Falling

# Price proximity to support/resistance
SUPPORT_RESISTANCE_RANGE = 0.01  # Within 1% = Price_AtSupport/AtResistance

# ============================================================================
# GRAPH DB QUERY PARAMETERS
# ============================================================================

# Maximum number of similar events to retrieve from graph DB
GRAPH_DB_SIMILAR_EVENTS_LIMIT = 5

# Minimum baseline win rate to consider a pattern valid
GRAPH_DB_MIN_BASELINE_WIN_RATE = 0.3  # 30%

# Alpha factor threshold (success_driver must beat baseline by this amount)
GRAPH_DB_ALPHA_THRESHOLD = 0.15  # 15% improvement over baseline

# Risk factor threshold (failure_driver must underperform baseline by this amount)
GRAPH_DB_RISK_THRESHOLD = 0.15   # 15% worse than baseline

# Prevalence threshold for common_context (must appear in X% of similar events)
GRAPH_DB_PREVALENCE_THRESHOLD = 0.60  # 60%

# ============================================================================
# VECTOR DB SIMILARITY THRESHOLDS
# ============================================================================

# Minimum similarity score to consider a match (0.0 to 1.0)
VECTOR_DB_SIMILARITY_THRESHOLD = 0.75

# Batch processing parameters
VECTOR_DB_BATCH_SIZE = 512

# ============================================================================
# LOGGING & DEBUGGING
# ============================================================================

# Enable debug logging for vector/graph DB operations
DEBUG_VECTOR_DB = False
DEBUG_GRAPH_DB = False

# Save checkpoint of vector DB after each update
AUTO_SAVE_VECTOR_DB_CHECKPOINT = True

# ============================================================================
# INTEGRATION CONTROL FLAGS
# ============================================================================

# Use vector DB for similarity search
USE_VECTOR_DB = VECTOR_DB_ENABLED

# Use graph DB for pattern analysis and trade reflection
USE_GRAPH_DB = GRAPH_DB_ENABLED

# Log all trades to graph DB (requires USE_GRAPH_DB=True)
LOG_TRADES_TO_GRAPH_DB = True

# Enable Agent S state classification (requires LLM)
USE_AGENT_S = True

# Enable Agent C reflection (requires USE_GRAPH_DB=True)
USE_AGENT_C_REFLECTION = True
